version: '3.3'

services:
    #service 1: definition of mysql database
    db:
      image: mysql:latest
      container_name: mysql-db2   
      environment:
        - MYSQL_ROOT_PASSWORD=andrea
        - MYSQL_USER=andrea
      ports:
        - "3306:3306"
      restart: always
      
    
    #service 3: definition of your spring-boot app 
    customerservice:                        #it is just a name, which will be used only in this file.
      image: myspringdb-service               #name of the image after dockerfile executes
      container_name: myspringdb-service-app  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8084:8084"                       #docker containter port with your os port
      restart: always
        
      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/myspringdb?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: andrea
        SPRING_DATASOURCE_PASSWORD: andrea
